### PR TITLE
Adding optional query parameter pass through filter feature.

### PR DESCRIPTION
**Pull request by IngvarKofoed**
As a developer I want to be able to have some specified query parameters being passed to the build URI with the linker. This will remove the tedious work of passing query parameters manually every time i build new URIs with the linker. 

Suggestions:
- Add option to the linkers method, to disallow query parameters to be passed. Consider this to be true as default.
- Better injection of allowed query parameters. 
- Make is possible to have different allowed parameters for each call to the linkers method.

I'm open for suggestions on how to make it better :)

### CODE REVIEW

**Comment by horsdal** [comment]
Thanks for submitting this.

The `IQueryFilter` looks like a more general concept. The signature of `Apply` does not constrain implementers to filter query parameters
But maybe an `IUriFilter` with the same `Apply` method would make sense. I'm thinking decorator pattern: The linker always sends URIs through `filter.Apply` just like with your changes. The default is the identity function - again like your code - and you can set up any number of filters in the bootstrapper- again much like your code, only a bit generalized:

 ```C#
public class Bootstrapper : DefaultNancyBootstrapper
{
  protected override void ApplicationStartup(TinyIoCContainer container, IPipelines pipelines)
  {
    // Other bootstrapper code here  
    container.Register<IUriFilter>(new MyCustomFilter(new EnsureHttps(new PassthroughQueryFilter(new[] { "foo" }))));
  }
}
```
where the `EnsureHttps` might be a filter provider with Nancy.Linker and `MyCustomFilter` is something application specific.

**Comment by IngvarKofoed** [comment]
Thanks for the feedback! Ill have a look at it after summer vacation :)

**Comment by horsdal** [comment]
Ping. Are we going to move on with this? I think we should. But I can take it if you haven't got the time.

**Comment by IngvarKofoed** [comment]
Yes, Ill move on this! :) The summer got in my way of looking at it ;) I will look at it in the next couple of days

**Comment by horsdal** [comment]
:cool:

**Comment by IngvarKofoed** [comment]
Please have a look at it now and let me know if there is anything that needs to be improved :)

**Comment by horsdal** [comment]
:heart: Thanks.

**Pull request closed without merging**
